# coding: utf-8

"""
    Smoker API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.client_settings_api import ClientSettingsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestClientSettingsApi(unittest.TestCase):
    """ClientSettingsApi unit test stubs"""

    def setUp(self):
        self.api = api.client_settings_api.ClientSettingsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_client_settings_current_get(self):
        """Test case for client_settings_current_get

        """
        pass

    def test_client_settings_current_post(self):
        """Test case for client_settings_current_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
