# coding: utf-8

"""
    Smoker API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.settings_client import SettingsClient  # noqa: E501
from swagger_client.rest import ApiException


class TestSettingsClient(unittest.TestCase):
    """SettingsClient unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSettingsClient(self):
        """Test SettingsClient"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.settings_client.SettingsClient()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
