# coding: utf-8

"""
    Smoker API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.measurement_smoker import MeasurementSmoker  # noqa: E501
from swagger_client.rest import ApiException


class TestMeasurementSmoker(unittest.TestCase):
    """MeasurementSmoker unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMeasurementSmoker(self):
        """Test MeasurementSmoker"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.measurement_smoker.MeasurementSmoker()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
