# coding: utf-8

"""
    Smoker API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.smoker_api import SmokerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSmokerApi(unittest.TestCase):
    """SmokerApi unit test stubs"""

    def setUp(self):
        self.api = api.smoker_api.SmokerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_smoker_get(self):
        """Test case for smoker_get

        """
        pass

    def test_smoker_post(self):
        """Test case for smoker_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
