version: '3.1'

services:

  mysql:
    container_name: mysql
    image: nagel/docker-raspberry-pi-mariadb:10.1.37
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_Password}
    volumes:
      - ${Volume}:/var/lib/mysql
    networks:
      - smokernet
    ports:
      - 3306:3306
    deploy:
      labels:
        local.description: "db"
      restart_policy:
        condition: on-failure
  
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    networks: 
      - smokernet
    ports:
      - 8080:8080

  api:
    container_name: service
    build: 
      context: ./api
    networks: 
      - smokernet
    depends_on: 
      - 'mysql'
    ports: 
      - 9090:80
      - 9091:443
    environment: 
      - connectionString=${connectionString}
      - Authority=https://identity:5123
    deploy:
      restart_policy:
        condition: on-failure

  auth:
    container_name: identity
    build: 
      context: ./AuthServer
    networks: 
      - smokernet
    depends_on: 
      - 'mysql'
    volumes:
      - /etc/letsencrypt/live/roadchiefs.ddns.net:/cert
    ports: 
      - 9090:80
      - 9091:443
    environment: 
      - connectionString=${connectionStringAuth}
      - ASPNETCORE_URLS=https://identity:443
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/cert/fullchain.pem
      - ASPNETCORE_Kestrel__Certificates__Default__Key=/cert/privkey.pem
      - ClientUrl=https://*:443
    deploy:
      restart_policy:
        condition: on-failure

networks:
  smokernet:
