version: '3.1'

services:

  mysql:
    image: nagel/docker-raspberry-pi-mariadb:10.1.37
    hostname: db
    environment:
      - MYSQL_ROOT_PASSWORD=SetThisToSomethingStrong!
    volumes:
      - /home/pi/db/lib/mysql:/var/lib/mysql
    networks:
      - smoker_net
    ports:
      - 3306:3306
    deploy:
      labels:
        local.description: "db"
      restart_policy:
        condition: on-failure

networks:
  smoker_net: