version: '3.1'

services:

  mysql:
    image: nagel/docker-raspberry-pi-mariadb:10.1.37
    hostname: db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_Password}
    volumes:
      - ${Volume}:/var/lib/mysql
    networks:
      - smoker_net
    ports:
      - 3306:3306
    deploy:
      labels:
        local.description: "db"
      restart_policy:
        condition: on-failure
  
  adminer:
    image: adminer
    restart: always
    networks: 
      - smoker_net
    ports:
      - 8080:8080


networks:
  smoker_net: