/**
 * Smoker API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface MeasurementSmoker {
    measurementId?: string;
    fireSensor?: number;
    contentSensor?: number;
    sensor1?: number;
    sensor2?: number;
    sensor3?: number;
    sensor4?: number;
    timeStamp?: Date;
    timeStampSmoker?: Date;
    openCloseState: number;
    isAutoMode: boolean;
    isSmokerConnected: boolean;
}
